# CE Restriction Tests
# Jenkins install param: edition=community
ns_server.ce_restrictions.CommunityEditionRestrictions:
    test_ce_5_node_limit_restart_persistence,nodes_init=5,services_init=kv-kv-kv-kv-kv,default_bucket=True,bucket_size=256,replicas=0,bucket_storage=couchstore,GROUP=P0
    test_ce_reject_ee_only_services,nodes_init=1,services_init=kv,default_bucket=True,bucket_size=256,replicas=0,bucket_storage=couchstore,GROUP=P0
    test_ce_allow_valid_service_combinations,nodes_init=1,services_init=kv,default_bucket=True,bucket_size=256,replicas=0,bucket_storage=couchstore,kv_quota_percent=25,index_quota_percent=25,fts_quota_percent=25,GROUP=P0
