bucket_collections.ten_k_collections.Ten_K_Collections:

    test_ten_k_collections_with_long_names,nodes_init=3,bucket_spec=multi_bucket.analytics_multi_bucket,services_init=kv:n1ql-kv:index-kv
    test_num_scope_limit,nodes_init=3,bucket_spec=multi_bucket.analytics_multi_bucket,services_init=kv:n1ql-kv:index-kv
    test_num_collection_limit,nodes_init=3,bucket_spec=multi_bucket.analytics_multi_bucket,services_init=kv:n1ql-kv:index-kv