[global]
username:root
password:couchbase
port:18091
n1ql_port:18093
index_port:19102
eventing_port:18096

[capella]
pod:
tenant_id:
project:
capella_user:
capella_pwd:
clusters:

override_token:
signup_token:
snaplogic_token:
account_id:

upgrade_image:
upgrade_server_version:
upgrade_release_id:
override_key:
image:
#release_id=1.0.67
server_version:
#image_hash:3418066c

secret_key:
access_key:

[membase]
rest_username:Administrator
rest_password:Couchbase@123