buckets:
  - name: "travel-sample"
    sample_bucket: True
    replicas: 1
    ramQuotaMB: 512
    scopes:
      - name: "agent_1"
        collections:
          - name: "meta_data"
          - name: "reviews"
          - name: "profile"
          - name: "search_history"
          - name: "flight_booking"
          - name: "booking_data"
          - name: "hotel_booking"
          - name: "eventing_meta"
          - name: "checkout_cart"
            maxTTL: 200
      - name: "agent_2"
        collections:
          - name: "meta_data"
          - name: "reviews"
          - name: "profile"
          - name: "search_history"
          - name: "flight_booking"
          - name: "booking_data"
          - name: "hotel_booking"
          - name: "eventing_meta"
          - name: "checkout_cart"
            maxTTL: 200
      - name: "agent_3"
        collections:
          - name: "meta_data"
          - name: "reviews"
          - name: "profile"
          - name: "search_history"
          - name: "flight_booking"
          - name: "booking_data"
          - name: "hotel_booking"
          - name: "eventing_meta"
          - name: "checkout_cart"
            maxTTL: 300
      - name: "agent_4"
        collections:
          - name: "meta_data"
          - name: "reviews"
          - name: "profile"
          - name: "search_history"
          - name: "flight_booking"
          - name: "booking_data"
          - name: "hotel_booking"
          - name: "eventing_meta"
          - name: "checkout_cart"
            maxTTL: 600
      - name: "agent_5"
        collections:
          - name: "meta_data"
          - name: "reviews"
          - name: "profile"
          - name: "search_history"
          - name: "flight_booking"
          - name: "booking_data"
          - name: "hotel_booking"
          - name: "eventing_meta"
          - name: "checkout_cart"
            maxTTL: 900

  - name: "couchstore"
    sample_bucket: False
    replicas: 1
    ramQuotaMB: 512
    bucketType: "couchbase"
    storageBackend: "couchstore"
    scopes:
      - name: "scope_1"
        collections:
          - name: "collection_1"
          - name: "collection_2"
            maxTTL: 200
      - name: "scope_2"
        collections:
          - name: "collection_3"
          - name: "collection_4"
          - name: "collection_5"
            maxTTL: 60

  - name: "magma"
    sample_bucket: False
    replicas: 1
    ramQuotaMB: 256
    bucketType: "couchbase"
    storageBackend: "magma"
    scopes:
      - name: "scope_1"
        collections:
          - name: "collection_1"
          - name: "collection_2"
            maxTTL: 200
      - name: "scope_2"
        collections:
          - name: "collection_3"
          - name: "collection_4"
          - name: "collection_5"
            maxTTL: 60
      - name: "scope_3"
        collections:
          - name: "collection_6"
          - name: "collection_7"
          - name: "collection_8"
            maxTTL: 60

  - name: "ephemeral"
    sample_bucket: False
    replicas: 1
    ramQuotaMB: 100
    bucketType: "ephemeral"
    scopes:
      - name: "scope_1"
        collections:
          - name: "collection_1"
          - name: "collection_2"
            maxTTL: 30
      - name: "scope_2"
        collections:
          - name: "collection_3"
          - name: "collection_4"
          - name: "collection_5"
