rbac_roles:
  - bucket: "travel-sample"
    roles:
      - user_name: "bucket_admin"
        password: "Bucket_admin@123"
        roles:
          - "bucket_admin[travel-sample]"
          - "query_manage_index[travel-sample]"
          - "query_system_catalog"
      - user_name: "guest"
        password: "Guest@123"
        roles:
          - "query_select[travel-sample]"
          - "query_use_sequential_scans[travel-sample]"
      - user_name: "cbas_admin"
        password: "Cbas_admin@123"
        select_bucket: False
        roles:
          - "analytics_admin"
          - "analytics_manager[*]"
      - user_name: "user_query"
        password: "User_query@123"
        roles:
          - "query_select[travel-sample]"
          - "query_update[travel-sample]"
      - user_name: "user_manager"
        password: "User_manager@123"
        roles:
          - "data_reader[travel-sample]"
          - "data_writer[travel-sample]"
          - "query_select[travel-sample]"
      - user_name: "user_booking"
        password: "User_booking@123"
        roles:
          - "data_reader[travel-sample]"
          - "data_writer[travel-sample]"
      - user_name: "review_writer"
        password: "Review_writer@123"
        roles:
          - "data_reader[travel-sample]"
          - "data_writer[travel-sample]"
      - user_name: "bucket_data_writer"
        password: "Bucket_data_writer@123"
        roles:
          - "data_writer[travel-sample]"
          - "query_select[travel-sample]"
      - user_name: "airline_admin"
        password: "Airline_admin@123"
        roles:
          - "data_reader[travel-sample]"
          - "data_writer[travel-sample]"
      - user_name: "airline_booking"
        password: "Airline_booking@123"
        roles:
          - "data_reader[travel-sample]"
          - "data_writer[travel-sample]"
          - "query_select[travel-sample]"
          - "query_update[travel-sample]"
          - "query_use_sequential_scans[travel-sample]"
      - user_name: "hotel_admin"
        password: "Hotel_admin@123"
        roles:
          - "data_reader[travel-sample]"
          - "data_writer[travel-sample]"
      - user_name: "hotel_booking"
        password: "Hotel_booking@123"
        roles:
          - "data_reader[travel-sample]"
          - "data_writer[travel-sample]"

  - bucket: "couchstore"
    roles:
      - user_name: "couchstore_admin"
        password: "password"
        roles:
          - "bucket_admin[couchstore]"
          - "data_writer[couchstore]"

  - bucket: "magma"
    roles:
      - user_name: "magma_admin"
        password: "password"
        roles:
          - "bucket_admin[magma]"
          - "data_writer[magma]"

  - bucket: "ephemeral"
    roles:
      - user_name: "eph_admin"
        password: "password"
        roles:
          - "bucket_admin[ephemeral]"
          - "data_writer[ephemeral]"
