lighthouse.collector.collector_tests.CollectorTests.test_get_collector_settings_returns_defaults,nodes_init=2|2,num_of_clusters=2,ucp_port=8080
lighthouse.collector.collector_tests.CollectorTests.test_verify_setting_of_configs,nodes_init=2|2,num_of_clusters=2,ucp_port=8080
lighthouse.collector.collector_tests.CollectorTests.test_verify_telemetry_accuracy,nodes_init=2|2,num_of_clusters=2,ucp_port=8080
lighthouse.collector.collector_tests.CollectorTests.test_verify_cluster_aggregate_telemetry,nodes_init=2|2,num_of_clusters=2,ucp_port=8080
lighthouse.collector.collector_tests.CollectorTests.test_node_rebalance_reflected_on_portal,nodes_init=3|2,num_of_clusters=2,ucp_port=8080
lighthouse.collector.collector_tests.CollectorTests.test_node_rebalance_reflected_on_portal,nodes_init=3|2,num_of_clusters=2,ucp_port=8080,master_node=true
