###################################################################################################
# Test GROUPING:
# Tests taking longer than an hour have been removed from being executed in the sanity pipeline.

# Therefore a certain Grouping format has been used in all the Capella v4 REST API conf files.
#     - Group RT : The Rate Limiting tests have this associated with them.

# Some Params can be specified while running tests in the pipeline or locally by editing the file or passing them in the test configuration.
#     - server_version : The server version for capella cluster to be deployed. DEFAULT = 7.6
###################################################################################################

Capella.RestAPIv4.Billing.categorized_billing.CategorizedBilling:
    test_api_path,GROUP=P0
    test_authorization,GROUP=P0
    test_query_parameters,GROUP=P0
    test_multiple_requests_using_API_keys_with_same_role_which_has_access,GROUP=P0;RT
    test_multiple_requests_using_API_keys_with_diff_role,GROUP=P0;RT
    test_categorized_billing_without_filter,GROUP=P0
    test_categorized_billing_with_filter,GROUP=P0

Capella.RestAPIv4.Billing.itemized_per_cluster.ItemizedPerCluster:
    test_api_path,GROUP=P0
    test_authorization,GROUP=P0
    test_query_parameters,GROUP=P0
    test_multiple_requests_using_API_keys_with_same_role_which_has_access,GROUP=P0;RT
    test_multiple_requests_using_API_keys_with_diff_role,GROUP=P0;RT
    test_itemized_per_cluster_date_ranges,GROUP=P0
    test_itemized_per_cluster_negative_dates,GROUP=P0
    test_itemized_per_cluster_individual_categories,GROUP=P0
    test_itemized_per_cluster_random_category_combos,GROUP=P0
    test_itemized_per_cluster_all_categories,GROUP=P0

Capella.RestAPIv4.Billing.download_categorized_in_cvs.DownloadCategories:
    test_api_path,GROUP=P0
    test_authorization,GROUP=P0
    test_query_parameters,GROUP=P0
    test_multiple_requests_using_API_keys_with_same_role_which_has_access,GROUP=P0;RT
    test_multiple_requests_using_API_keys_with_diff_role,GROUP=P0;RT
    test_download_categories_in_csv_date_ranges,GROUP=P0
    test_download_categories_in_csv_negative_dates,GROUP=P0
    test_download_categories_in_csv_individual_categories,GROUP=P0
    test_download_categories_in_csv_random_category_combos,GROUP=P0
    test_download_categories_in_csv_all_categories,GROUP=P0

Capella.RestAPIv4.Billing.download_itemized_per_cluster_in_cvs.DownloadItemizedPerCluster:
    test_api_path,GROUP=P0
    test_authorization,GROUP=P0
    test_query_parameters,GROUP=P0
    test_multiple_requests_using_API_keys_with_same_role_which_has_access,GROUP=P0;RT
    test_multiple_requests_using_API_keys_with_diff_role,GROUP=P0;RT
    test_download_itemized_per_cluster_in_csv_date_ranges,GROUP=P0
    test_download_itemized_per_cluster_in_csv_negative_dates,GROUP=P0
    test_download_itemized_per_cluster_in_csv_individual_categories,GROUP=P0
    test_download_itemized_per_cluster_in_csv_random_category_combos,GROUP=P0
    test_download_itemized_per_cluster_in_csv_all_categories,GROUP=P0

Capella.RestAPIv4.Billing.get_prepaid_credit_consumption.GetPrepaidCreditConsumption:
    test_api_path,GROUP=P0
    test_authorization,GROUP=P0
    test_query_parameters,GROUP=P0
    test_multiple_requests_using_API_keys_with_same_role_which_has_access,GROUP=P0;RT
    test_multiple_requests_using_API_keys_with_diff_role,GROUP=P0;RT
    test_pagination_valid_params,GROUP=P0
    test_pagination_invalid_params,GROUP=P0

Capella.RestAPIv4.Billing.pay_as_you_go.PayAsYouGo:
    test_api_path,GROUP=P0
    test_authorization,GROUP=P0
    test_query_parameters,GROUP=P0
    test_multiple_requests_using_API_keys_with_same_role_which_has_access,GROUP=P0;RT
    test_multiple_requests_using_API_keys_with_diff_role,GROUP=P0;RT
    test_pay_as_you_go,GROUP=P0
