###################################################################################################
# Test GROUPING:
# Sanity coverage for Cloud Snapshot Backups & Restore v4 APIs.
###################################################################################################

Capella.RestAPIv4.CloudSnapshotBackups.list_project_cloud_snapshot_backups.ListProjectLevelCloudSnapshotBackups:
    test_api_path,GROUP=P0;functional
    test_authorization,GROUP=P0;security

Capella.RestAPIv4.CloudSnapshotBackups.list_cloud_snapshot_backups.ListCloudSnapshotBackups:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security

Capella.RestAPIv4.CloudSnapshotBackups.create_cloud_snapshot_backup.CreateCloudSnapshotBackup:
    test_api_path,GROUP=P2;functional
    test_authorization,GROUP=P2;security
    test_payload,GROUP=P2;functional

Capella.RestAPIv4.CloudSnapshotBackups.list_cloud_snapshot_backup_regions.ListCloudSnapshotBackupRegions:
    test_api_path,GROUP=P3;functional
    test_authorization,GROUP=P3;security

Capella.RestAPIv4.CloudSnapshotBackups.list_cloud_snapshot_restores.ListCloudSnapshotRestores:
    test_api_path,GROUP=P4;functional
    test_authorization,GROUP=P4;security

Capella.RestAPIv4.CloudSnapshotBackups.update_cloud_snapshot_backup_retention.UpdateCloudSnapshotBackupRetention:
    test_api_path,GROUP=P5;functional
    test_authorization,GROUP=P5;security
    test_payload,GROUP=P5;functional

Capella.RestAPIv4.CloudSnapshotBackups.delete_cloud_snapshot_backup.DeleteCloudSnapshotBackup:
    test_api_path,GROUP=P6;functional
    test_authorization,GROUP=P6;security

Capella.RestAPIv4.CloudSnapshotBackups.restore_cloud_snapshot_backup.RestoreCloudSnapshotBackup:
    test_api_path,GROUP=P7;functional
    test_authorization,GROUP=P7;security
    test_payload,GROUP=P7;functional

Capella.RestAPIv4.CloudSnapshotBackups.clone_cloud_snapshot_backup.CloneCloudSnapshotBackup:
    test_api_path,GROUP=P8;functional
    test_authorization,GROUP=P8;security
    test_payload,GROUP=P8;functional
