###################################################################################################
# File for sanity testing for Capella v4 CMEK APIs.
#
# Test GROUPING:
#     - Group P0 : Organization-level CMEK APIs
#     - Group P1 : Project-level CMEK APIs
#     - Group P2 : Cluster-level CMEK APIs
#     - Group RT : Rate Limiting tests
###################################################################################################

Capella.RestAPIv4.Organizations.list_cloud_accounts.ListCloudAccounts:
    test_api_path,GROUP=P0;functional
    test_authorization,GROUP=P0;security;S1

Capella.RestAPIv4.Organizations.enable_cmek_providers.EnableCMEKProvider:
    test_api_path,GROUP=P0;functional
    test_authorization,GROUP=P0;security;S1
    test_payload,GROUP=P0;functional

Capella.RestAPIv4.Organizations.get_cmek_azure_application.GetCMEKAzureApplication:
    test_api_path,GROUP=P0;functional
    test_authorization,GROUP=P0;security;S1

Capella.RestAPIv4.Organizations.list_cmek.ListCMEK:
    test_api_path,GROUP=P0;functional
    test_authorization,GROUP=P0;security;S1

Capella.RestAPIv4.Organizations.create_cmek.CreateCMEK:
    test_api_path,GROUP=P0;functional
    test_authorization,GROUP=P0;security;S1
    test_payload,GROUP=P0;functional

Capella.RestAPIv4.Organizations.get_cmek.GetCMEK:
    test_api_path,GROUP=P0;functional
    test_authorization,GROUP=P0;security;S1

Capella.RestAPIv4.Organizations.update_cmek.UpdateCMEK:
    test_api_path,GROUP=P0;functional
    test_authorization,GROUP=P0;security;S1
    test_payload,GROUP=P0;functional

Capella.RestAPIv4.Organizations.delete_cmek.DeleteCMEK:
    test_api_path,GROUP=P0;functional
    test_authorization,GROUP=P0;security;S1

Capella.RestAPIv4.Organizations.list_cmek_history.ListCMEKHistory:
    test_api_path,GROUP=P0;functional
    test_authorization,GROUP=P0;security;S1

Capella.RestAPIv4.Organizations.enable_project_cmek_providers.EnableProjectCMEKProvider:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1
    test_payload,GROUP=P1;functional

Capella.RestAPIv4.Organizations.get_project_cmek_azure_application.GetProjectCMEKAzureApplication:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1

Capella.RestAPIv4.Organizations.project_cmek.ProjectCMEK:
    test_get_api_path,GROUP=P1;functional
    test_post_api_path,GROUP=P1;functional

Capella.RestAPIv4.Organizations.project_cmek_by_id.ProjectCMEKById:
    test_get_api_path,GROUP=P1;functional
    test_put_api_path,GROUP=P1;functional
    test_delete_api_path,GROUP=P1;functional

Capella.RestAPIv4.Clusters.unassociate_cmek.UnassociateCMEK:
    test_api_path,GROUP=P2;functional
    test_authorization,GROUP=P2;security;S2
