###################################################################################################
# File for sanity testing for Capella v4 Data API APIs.
#
# Test GROUPING:
#     - Group P0 : Data API state APIs (GET / PUT)
#     - Group P1 : Data API Private Endpoint Command API
#     - Group P2 : Data API Private Endpoints APIs (list / associate / unassociate)
#     - Group RT : Rate Limiting tests
###################################################################################################

Capella.RestAPIv4.DataAPI.get_data_api.GetDataAPI:
    test_api_path,GROUP=P0;functional
    test_authorization,GROUP=P0;security;S1

Capella.RestAPIv4.DataAPI.update_data_api.UpdateDataAPI:
    test_api_path,GROUP=P0;functional
    test_authorization,GROUP=P0;security;S1
    test_payload,GROUP=P0;functional

Capella.RestAPIv4.DataAPI.data_api_private_endpoint_command.PostDataAPIEndpointCommand:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S2
    test_payload,GROUP=P1;functional

Capella.RestAPIv4.DataAPI.list_data_api_private_endpoints.ListDataAPIEndpoints:
    test_api_path,GROUP=P2;functional
    test_authorization,GROUP=P2;security;S2

Capella.RestAPIv4.DataAPI.associate_data_api_private_endpoints.PostDataAPIAssociate:
    test_api_path,GROUP=P2;functional
    test_authorization,GROUP=P2;security;S2

Capella.RestAPIv4.DataAPI.unassociate_data_api_private_endpoints.PostDataAPIUnassociate:
    test_api_path,GROUP=P2;functional
    test_authorization,GROUP=P2;security;S2
