###################################################################################################
# File for sanity testing for Capella v4 RBAC Roles & User APIs
###################################################################################################

Capella.RestAPIv4.DatabaseCredentials.create_list_credentials.CreateDatabaseCredential:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1
    test_payload,GROUP=P1;functional
Capella.RestAPIv4.DatabaseCredentials.create_list_credentials.ListDatabaseCredentials:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1
Capella.RestAPIv4.DatabaseCredentials.get_update_delete_credential.GetDatabaseCredential:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1
Capella.RestAPIv4.DatabaseCredentials.get_update_delete_credential.UpdateDatabaseCredential:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1
    test_payload,GROUP=P1;functional
Capella.RestAPIv4.DatabaseCredentials.get_update_delete_credential.DeleteDatabaseCredential:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1

Capella.RestAPIv4.DatabaseRoles.create_list_roles.CreateDatabaseRole:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1
    test_payload,GROUP=P1;functional
Capella.RestAPIv4.DatabaseRoles.create_list_roles.ListDatabaseRoles:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1
Capella.RestAPIv4.DatabaseRoles.get_update_delete_role.GetDatabaseRole:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1
Capella.RestAPIv4.DatabaseRoles.get_update_delete_role.UpdateDatabaseRole:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1
    test_payload,GROUP=P1;functional
Capella.RestAPIv4.DatabaseRoles.get_update_delete_role.DeleteDatabaseRole:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1
Capella.RestAPIv4.DatabaseRoles.list_privileges.ListCapellaPrivileges:
    test_api_path,GROUP=P1;functional
    test_authorization,GROUP=P1;security;S1
