###################################################################################################
# File for sanity testing for Capella v4 Eventing Functions APIs.
#
# Test GROUPING:
#     - Group P16 : Eventing Functions (9 endpoints)
#         - Create / List / Get / Update / Delete eventing function
#         - Get / Update eventing function code
#         - Update eventing function activation state
#         - Get eventing function logs
###################################################################################################

Capella.RestAPIv4.EventingFunctions.create_eventing_function.CreateEventingFunction:
    test_api_path,GROUP=P16;functional
    test_authorization,GROUP=P16;security;S1
    test_payload,GROUP=P16;functional
Capella.RestAPIv4.EventingFunctions.list_eventing_functions.ListEventingFunctions:
    test_api_path,GROUP=P16;functional
    test_authorization,GROUP=P16;security;S1
Capella.RestAPIv4.EventingFunctions.get_eventing_function.GetEventingFunction:
    test_api_path,GROUP=P16;functional
    test_authorization,GROUP=P16;security;S1
Capella.RestAPIv4.EventingFunctions.update_eventing_function.UpdateEventingFunction:
    test_api_path,GROUP=P16;functional
    test_authorization,GROUP=P16;security;S1
    test_payload,GROUP=P16;functional
Capella.RestAPIv4.EventingFunctions.delete_eventing_function.DeleteEventingFunction:
    test_api_path,GROUP=P16;functional
    test_authorization,GROUP=P16;security;S1
Capella.RestAPIv4.EventingFunctions.get_eventing_function_code.GetEventingFunctionCode:
    test_api_path,GROUP=P16;functional
    test_authorization,GROUP=P16;security;S1
Capella.RestAPIv4.EventingFunctions.update_eventing_function_code.UpdateEventingFunctionCode:
    test_api_path,GROUP=P16;functional
    test_authorization,GROUP=P16;security;S1
    test_payload,GROUP=P16;functional
Capella.RestAPIv4.EventingFunctions.update_eventing_function_activation_state.UpdateEventingFunctionActivationState:
    test_api_path,GROUP=P16;functional
    test_authorization,GROUP=P16;security;S1
    test_payload,GROUP=P16;functional
Capella.RestAPIv4.EventingFunctions.get_eventing_function_logs.GetEventingFunctionLogs:
    test_api_path,GROUP=P16;functional
    test_authorization,GROUP=P16;security;S1
