Columnar.update_statement.UpdateStatementTest:
    test_update_existing_field,GROUP=sanity
    test_update_non_existing_field,GROUP=sanity
    test_update_multiple_fields,GROUP=sanity
    test_remove_field_using_missing,GROUP=sanity
    test_update_field_multiple_times,GROUP=sanity
    test_update_delete_field,GROUP=sanity
    test_update_multi_datatypes,GROUP=sanity
    test_add_new_field_from_computed_value,GROUP=sanity
    test_add_timestamp_field,GROUP=sanity
    test_update_nested_existing_field,GROUP=sanity
    test_add_nested_non_existing_field,GROUP=sanity
    test_update_null_to_non_null,GROUP=sanity
    test_delete_non_existing_field_noop,GROUP=sanity
    test_update_primary_key_negative,GROUP=sanity
    test_returning_clause,GROUP=sanity
    test_update_array_without_pos,GROUP=sanity
    test_update_array_with_pos,GROUP=sanity
    test_update_multiple_array_elements,GROUP=sanity
    test_update_multiple_array_elements_with_condition,GROUP=sanity
    test_delete_multiple_array_elements,GROUP=sanity
    test_delete_array_elements_with_condition,GROUP=sanity