epengine.rate_limiting_tests.KVRateLimitingTests:
    test_bucket_limit_crud_and_cli,nodes_init=1,GROUP=P0,bucket_throttle_reserved=5000,bucket_throttle_hard_limit=10000
    test_limit_enforcement,nodes_init=1,GROUP=P0,bucket_throttle_reserved=100,bucket_throttle_hard_limit=200
    test_enable_disable_rate_limiting_rest,nodes_init=1,GROUP=P0,bucket_throttle_reserved=5000,bucket_throttle_hard_limit=10000
    test_soft_limit_throttling,nodes_init=1,GROUP=P0,bucket_storage=magma,bucket_throttle_reserved=100,bucket_throttle_hard_limit=10000
    test_hard_limit_rejection,nodes_init=1,GROUP=P0,bucket_type=ephemeral,bucket_eviction_policy=noEviction,bucket_throttle_reserved=50,bucket_throttle_hard_limit=100
    test_transaction_rate_limiting,nodes_init=1,GROUP=P0,bucket_throttle_reserved=500,bucket_throttle_hard_limit=1000
