epengine.rate_limiting_tests.KVRateLimitingTests:
    test_bucket_limit_crud_and_cli,nodes_init=1,GROUP=P0,bucket_throttle_reserved=5000,bucket_throttle_hard_limit=10000
    test_limit_enforcement,nodes_init=1,GROUP=P0,bucket_throttle_reserved=100,bucket_throttle_hard_limit=200
    test_enable_disable_rate_limiting_rest,nodes_init=1,GROUP=P0,bucket_throttle_reserved=5000,bucket_throttle_hard_limit=10000
    test_soft_limit_throttling,nodes_init=1,GROUP=P0,bucket_storage=magma,bucket_throttle_reserved=100,bucket_throttle_hard_limit=10000
    test_hard_limit_rejection,nodes_init=1,GROUP=P0,bucket_type=ephemeral,bucket_eviction_policy=noEviction,bucket_throttle_reserved=50,bucket_throttle_hard_limit=100
    test_transaction_rate_limiting,nodes_init=1,GROUP=P0,bucket_throttle_reserved=500,bucket_throttle_hard_limit=1000
    test_sdk_rate_limited_exception,nodes_init=1,GROUP=P0,bucket_throttle_reserved=50,bucket_throttle_hard_limit=100
    test_prometheus_throttle_metrics,nodes_init=1,GROUP=P0,bucket_throttle_reserved=100,bucket_throttle_hard_limit=10000
    test_couchstore_and_magma_throttle,nodes_init=1,GROUP=P0,bucket_storage=couchstore,bucket_throttle_reserved=100,bucket_throttle_hard_limit=10000
    test_couchstore_and_magma_throttle,nodes_init=1,GROUP=P0,bucket_storage=magma,bucket_throttle_reserved=100,bucket_throttle_hard_limit=10000
    test_sync_gateway_backoff_simulation,nodes_init=1,GROUP=P0,bucket_throttle_reserved=100,bucket_throttle_hard_limit=200

epengine.rate_limiting_tests.RateLimitingUpgradeTests:
    test_rate_limit_in_mixed_mode_cluster,nodes_init=3,upgrade_type=online_swap,upgrade_chain=7.6.7,bucket_throttle_reserved=6000,bucket_throttle_hard_limit=12000,GROUP=P0
    test_rate_limit_after_full_upgrade,nodes_init=3,upgrade_type=online_swap,upgrade_chain=7.6.7,bucket_throttle_reserved=6000,bucket_throttle_hard_limit=12000,GROUP=P0
