subdoc.subdoc_xattr.XattrTests:
    test_transitions,loadtype=regular,workload=workload_a,load_docs_using=default_loader
    test_transitions,loadtype=regular,workload=workload_b,load_docs_using=default_loader
    test_transitions,loadtype=regular,workload=workload_c,load_docs_using=default_loader
    test_transitions,loadtype=regular,workload=workload_d,load_docs_using=default_loader
    test_transitions,loadtype=regular,workload=workload_f,load_docs_using=default_loader
    test_transitions,loadtype=regular,workload=workload_g,load_docs_using=default_loader
    test_transitions,loadtype=regular,workload=workload_h,load_docs_using=default_loader
    test_transitions,loadtype=regular,workload=workload_i,load_docs_using=default_loader
    test_transitions,loadtype=regular,workload=workload_j,load_docs_using=default_loader
    test_shadow_fragmentation,doc_size=4096,cycle_size=500000,load_docs_using=default_loader
