upgrade.security_upgrade.SecurityUpgradeTests:
    # 7.2.x --> 8.x.x
    # Failover Recovery Upgrade Tests
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=7.2.9,nodes_upgrade=3,upgrade_type=failover_delta_recovery,GROUP=P0;7_2
    # Full Offline Upgrade Tests
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=7.2.9,nodes_upgrade=3,upgrade_type=full_offline,GROUP=P0;7_2
    # Swap Rebalance Upgrade Tests
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=7.2.9,nodes_upgrade=3,upgrade_type=online_swap,GROUP=P0;7_2

    # 7.6.x --> 8.x.x
    # Failover Recovery Upgrade Tests
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=7.6.6,nodes_upgrade=3,upgrade_type=failover_delta_recovery,GROUP=P0;7_6
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=7.6.9,nodes_upgrade=3,upgrade_type=failover_delta_recovery,GROUP=P0;7_6
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=7.6.12,nodes_upgrade=3,upgrade_type=failover_delta_recovery,GROUP=P0;7_6
    # Full Offline Upgrade Tests
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=7.6.5,nodes_upgrade=3,upgrade_type=full_offline,GROUP=P0;7_6
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=7.6.8,nodes_upgrade=3,upgrade_type=full_offline,GROUP=P0;7_6
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=7.6.11,nodes_upgrade=3,upgrade_type=full_offline,GROUP=P0;7_6
    # Swap Rebalance Upgrade Tests
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=7.6.6,nodes_upgrade=3,upgrade_type=online_swap,GROUP=P0;7_6
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=7.6.9,nodes_upgrade=3,upgrade_type=online_swap,GROUP=P0;7_6
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=7.6.12,nodes_upgrade=3,upgrade_type=online_swap,GROUP=P0;7_6

    # 8.0.x --> 8.x.x
    # Failover Recovery Upgrade Tests
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=8.0.0,nodes_upgrade=3,upgrade_type=failover_delta_recovery,GROUP=P0;8_0
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=8.0.1,nodes_upgrade=3,upgrade_type=failover_delta_recovery,GROUP=P0;8_0
    # Full Offline Upgrade Tests
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=8.0.0,nodes_upgrade=3,upgrade_type=full_offline,GROUP=P0;8_0
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=8.0.1,nodes_upgrade=3,upgrade_type=full_offline,GROUP=P0;8_0
    # Swap Rebalance Upgrade Tests
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=8.0.0,nodes_upgrade=3,upgrade_type=online_swap,GROUP=P0;8_0
    test_upgrade_ro_admin,nodes_init=3,upgrade_chain=8.0.1,nodes_upgrade=3,upgrade_type=online_swap,GROUP=P0;8_0
