Columnar.onprem.ea_upgrade.EnterpriseAnalyticsUpgrade:
    test_swap_rebalance_upgrade,GROUP=upgrade,nodes_init=3,services_init=columnar-kv:cbas-kv:cbas-kv:cbas
    test_failover_upgrade,GROUP=upgrade,nodes_init=3,services_init=columnar-kv:cbas-kv:cbas
    test_offline_upgrade,GROUP=upgrade,nodes_init=3,services_init=columnar-kv:cbas-kv:cbas
